# Generated by Django 4.0.6 on 2022-07-09 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Taking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='feeding date')),
                ('time', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('D', 'Dinner')], default='M', max_length=1)),
                ('sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sup')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='sup',
            name='types',
            field=models.ManyToManyField(to='main_app.type'),
        ),
    ]
