# Generated by Django 4.0.6 on 2022-07-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taking',
            name='time',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1),
        ),
    ]
